import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        paddingTop: 60,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        fontSize: 18,
        color: '#7f8c8d',
        fontWeight: '600',
    },
    header: {
        paddingHorizontal: 20,
        marginBottom: 20,
    },
    title: {
        fontSize: 24,
        fontWeight: '800',
        color: '#2c3e50',
        textAlign: 'center',
        marginBottom: 40,
        paddingTop: 40,
    },
    statsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        backgroundColor: '#ffffff',
        borderRadius: 16,
        padding: 16,
        marginHorizontal: 10,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 8,
        elevation: 4,
    },
    statItem: {
        alignItems: 'center',
    },
    statNumber: {
        fontSize: 24,
        fontWeight: '800',
        color: '#2c3e50',
    },
    statLabel: {
        fontSize: 12,
        color: '#7f8c8d',
        fontWeight: '600',
        textTransform: 'uppercase',
        marginTop: 4,
    },
    listContainer: {
        paddingHorizontal: 20,
        paddingBottom: 20,
    },
    issueWrapper: {
        marginBottom: 16,
    },
    issueTouchable: {
        borderRadius: 20,
        overflow: 'hidden',
    },
    issueCard: {
        borderRadius: 20,
        padding: 20,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 8 },
        shadowRadius: 16,
        elevation: 8,
        borderWidth: 1,
        borderColor: '#f1f3f4',
    },
    priorityBar: {
        position: 'absolute',
        left: 0,
        top: 0,
        bottom: 0,
        width: 4,
        borderTopLeftRadius: 20,
        borderBottomLeftRadius: 20,
    },
    issueHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 12,
    },
    issueTitleSection: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        marginRight: 12,
    },
    issueIcon: {
        fontSize: 20,
        marginRight: 10,
    },
    issueTitleContainer: {
        flex: 1,
    },
    issueTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#2c3e50',
        marginBottom: 3,
    },
    issueId: {
        fontSize: 11,
        color: '#95a5a6',
        fontWeight: '600',
    },
    statusBadge: {
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 16,
        shadowColor: '#000',
        shadowOpacity: 0.2,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 4,
        elevation: 3,
    },
    statusBadgeText: {
        color: '#fff',
        fontSize: 10,
        fontWeight: '700',
        textTransform: 'uppercase',
    },
    locationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    locationIcon: {
        fontSize: 14,
        marginRight: 6,
    },
    locationText: {
        fontSize: 12,
        color: '#7f8c8d',
        fontWeight: '500',
        flex: 1,
    },
    descriptionText: {
        fontSize: 13,
        color: '#34495e',
        lineHeight: 18,
        marginBottom: 12,
    },
    issueFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: 10,
        borderTopWidth: 1,
        borderTopColor: '#ecf0f1',
    },
    timestampText: {
        fontSize: 10,
        color: '#95a5a6',
        fontWeight: '500',
    },
    tapHint: {
        fontSize: 10,
        color: '#3498db',
        fontWeight: '600',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.6)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    modalContainer: {
        width: '100%',
        maxWidth: 400,
    },
    modalContent: {
        borderRadius: 24,
        padding: 24,
        shadowColor: '#000',
        shadowOpacity: 0.3,
        shadowOffset: { width: 0, height: 16 },
        shadowRadius: 24,
        elevation: 16,
    },
    modalTitle: {
        fontSize: 22,
        fontWeight: '800',
        color: '#2c3e50',
        textAlign: 'center',
        marginBottom: 8,
    },
    modalSubtitle: {
        fontSize: 16,
        color: '#7f8c8d',
        textAlign: 'center',
        marginBottom: 24,
        fontWeight: '500',
    },
    statusOptions: {
        gap: 12,
        marginBottom: 24,
    },
    statusOptionTouchable: {
        borderRadius: 16,
        overflow: 'hidden',
    },
    statusOption: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        borderRadius: 16,
        borderWidth: 2,
        borderColor: 'transparent',
    },
    statusOptionSelected: {
        borderColor: '#ffffff40',
        shadowColor: '#000',
        shadowOpacity: 0.2,
        shadowOffset: { width: 0, height: 4 },
        shadowRadius: 8,
        elevation: 4,
    },
    statusOptionIcon: {
        fontSize: 20,
        marginRight: 12,
    },
    statusOptionText: {
        fontSize: 16,
        fontWeight: '700',
        flex: 1,
    },
    modalButtons: {
        flexDirection: 'row',
        gap: 12,
    },
    cancelButton: {
        flex: 1,
        paddingVertical: 16,
        borderRadius: 16,
        backgroundColor: '#ecf0f1',
        alignItems: 'center',
    },
    cancelButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#7f8c8d',
    },
    saveButtonTouchable: {
        flex: 1,
        borderRadius: 16,
        overflow: 'hidden',
    },
    saveButton: {
        paddingVertical: 16,
        alignItems: 'center',
        borderRadius: 16,
    },
    saveButtonText: {
        fontSize: 16,
        fontWeight: '700',
        color: '#fff',
    },

    issueImage: {
        width: '100%',
        height: 200,
        borderRadius: 20,
        marginBottom: 12,
        resizeMode: 'cover',
    },
});